//
// Created by sean on 24/05/2018.
//

#ifndef OSASSINGMENT_DEFENITIONS_H
#define OSASSINGMENT_DEFENITIONS_H
#define MAX_ARGS 255
#define MAX_BUFFFER 255
#define MAX_VAR_SIZE 255
#endif //OSASSINGMENT_DEFENITIONS_H
